### ISSUE TITLE
Livekit does not work on Chrome on Android 11 

### ISSUE THREAD

**Issue by zdrazdova** [livekit/components-js#1001]
### Select which package(s) are affected

\@livekit/components-react

### Describe the bug

In our app livekit does not work in Chrome on Android 11 because livekit does not see any Audio devices. I tried livekit meet to make sure the problem is in livekit and not on our side.

### Reproduction

1.) Open [meet.livekit.io](https://meet.livekit.io/) in Chrome on Android 11
2.) Allow permissions for Camera and Microphone
3.) Join call
4.) Open selection of audio devices - it is empty

I can not choose any audio device in waiting room
![WaitingRoom](https://github.com/user-attachments/assets/37a81fef-6138-4fca-aab1-4c03fcbebaf4)

In the call the selection of audio devices is empty
![MicrophoneSelection](https://github.com/user-attachments/assets/cf4a7d9d-ede1-47c1-90c1-12c86ccd926f)

For comparison selection of cameras looks ok
![CameraSelection](https://github.com/user-attachments/assets/e1ea0b6b-3bda-4581-8a02-1061576810a5)

### System Info

```shell
Android 11, Chrome
```

### Severity

blocking all usage of LiveKit

**Comment by lukasIO** [comment]
thanks for the report, which chrome version are you using?

**Comment by zdrazdova** [comment]
> thanks for the report, which chrome version are you using?

It is Chrome 129.0.6668.81

**Comment by lukasIO** [comment]
thanks! 
Can you post the complete client side logs of such a session on meet.livekit.io? 
I cannot reproduce this error with Android 11 on browserstack

**Comment by karam14** [comment]
Same issue on android 13 
 Chrome 129.0.6668.100

**Comment by lukasIO** [comment]
we tried to reproduce this with the Chrome version on android devices ranging from Android 11 to 14 and weren't able to. Could you provide the console debug logs and post a screenshot of the permissions you granted on the meet site (the little switches button to the left of the url)

**Comment by lukasIO** [comment]
the error indicates that you denied permissions to access the microphone. 
You can try to `Reset Permissions` in the permissions dialog and make sure that microphone access isn't restricted on a system level for chrome.

**Comment by davidliu** [comment]
Additionally check your Settings App -> Chrome -> Permissions to check if the microphone has been specifically blocked app wide.

**Comment by karam14** [comment]
That fixed the issue thanks! However I've tested it on 5 different Samsung devices and it seems that chrome have microphone permissions disabled by default app wide? Maybe is it an idea to inform users when permissions can't be obtained so that they can act accordingly?
> Additionally check your Settings App -> Chrome -> Permissions to check if the microphone has been specifically blocked app wide.

**Comment by lukasIO** [comment]
informing users is a good call, when implementing the components yourself you can do this via the `onMediaDeviceError` callback on the `LiveKitRoom` component
