### ISSUE TITLE
docs: fix typo

### ISSUE THREAD

**Issue by jjangga0214** [livekit/components-js#1008]
Hi.

As It seems there's no docs repo, I leave this here.

https://docs.livekit.io/agents/openai/client-apps/

<img width="654" alt="스크린샷 2024-10-09 오후 8 37 26" src="https://github.com/user-attachments/assets/ed6f4e7e-05c3-423c-a609-b3e1a0c3ac4a">

It should be `style`, not `styles`.

By the way, why isn't there a docs repo where I can publicly contribute directly?

**Comment by lukasIO** [comment]
thanks for the report, this is fixed and will be rolled out soon!

**Comment by jjangga0214** [comment]
@lukasIO Thank you. May I ask the reason the docs repo isn't public?
