### ISSUE TITLE
Sound distortion when the microphone is turned on

### ISSUE THREAD

**Issue by richthegxd** [livekit/components-js#1040]
### Select which package(s) are affected

\@livekit/components-react

### What I'm expect
Users are actively complaining about problems with Bluetooth headphones, by default in my application the microphone is turned off (always) and in PreJoin users are also not given the choice to turn it on or off. Users complain that if they enter a room with Bluetooth headphones and turn on their microphone, they begin to hear the rest of the participants poorly, as if some kind of sound filter is turned on.

This bug can also be caught in your application https://meet.livekit.io /. In the PreJoin component, your microphone should be turned off by default, when you get into a room with Bluetooth headphones and turn on your microphone, you start to hear the rest of the participants poorly.

Actually, it doesn't look like a LiveKit bug anymore, but rather some kind of mobile device feature, but still, can you see how to fix it and is it possible to fix it?

I also tried to record a video with this bug, but when I turn on the microphone, there is no sound at all on the recording

### Reproduction

1. Go to https://meet.livekit.io with Bluetooth headphones connected
2. Turn off your microphone in the PreJoin component
3. Refresh the page (we keep that we turned off our microphone and therefore it will also be turned off when the page is reloaded)
4. We go into the room itself, in which there are other users, they must speak
5. While these users are talking, we turn on our microphone and hear that the audio tracks of other participants have become hard to hear

### System Info

```shell
System:
    OS: Linux 6.8 Ubuntu 24.04.1 LTS 24.04.1 LTS (Noble Numbat)
    CPU: (8) x64 AMD Ryzen 5 5600X 6-Core Processor
    Memory: 13.08 GB / 19.19 GB
    Container: Yes
    Shell: 5.2.21 - /bin/bash
  Binaries:
    Node: 20.17.0 - ~/.nvm/versions/node/v20.17.0/bin/node
    npm: 10.8.2 - ~/.nvm/versions/node/v20.17.0/bin/npm
    pnpm: 9.12.1 - ~/.nvm/versions/node/v20.17.0/bin/pnpm
  Browsers:
    Chrome: 130.0.6723.116
  npmPackages:
    livekit-client: 2.7.0 => 2.7.0
```

### Severity

annoyance

**Comment by richthegxd** [comment]
I thought it was possible that the stability of the audio output was changing in this case, but on mobile devices, the [useMediaDeviceSelect ](https://docs.livekit.io/reference/components/react/hook/usemediadeviceselect/) hook, with the parameter 

```
{
 kind: "audiooutput"
}
```

does not give away any devices

**Comment by richthegxd** [comment]
In the room options, I tried to turn on noise reduction and echo cancellation, but it also did not work

```
const roomOptions: RoomOptions = useMemo(
    () => ({
      videoCaptureDefaults: {
        deviceId: userChoices.videoDeviceId,
        resolution: VideoPresets.h720
      },
      publishDefaults: {
        dtx: false,
        videoSimulcastLayers: [VideoPresets.h540, VideoPresets.h216],
        red: false,
        videoCodec: "vp9"
      },
      audioCaptureDefaults: {
        deviceId: userChoices.audioDeviceId || "default",
        // No effect
        autoGainControl: false,
        noiseSuppression: false,
        echoCancellation: false,
      },
      adaptiveStream: {
        pixelDensity: "screen",
        pauseVideoInBackground: true
      },
      dynacast: true,
      stopLocalTrackOnUnpublish: true
    }),
    []
  );
```

**Comment by richthegxd** [comment]
So far, the only working fix is the mandatory inclusion of the microphone when connected on mobile devices, something like this:

```
const isMobile = isMobileDevice();

<LiveKitRoom audio={isMobile}>
   ...
</LiveKitRoom>
```

**Comment by lukasIO** [comment]
Bluetooth headsets have 2 modes of operation.
Mode 1: high quality for listening to music
Mode 2: low quality for voice communications

Mode 1 is the default. As soon as you switch your headset on, it is in this mode and you're able to listen to your media player/streaming website in high quality.
Mode 2 is activated as soon as some app activates the headset microphone.

This is (unfortunately) how bluetooth headsets work and there's nothing we can do about it.

**Comment by richthegxd** [comment]
Well, it happens...

I also had such a case, unfortunately, I could not reproduce it, maybe you have come across something similar?

> If you enter a room from a phone with headphones on, when you turn on the microphone, the sound goes to the main speaker of the phone, the headphones turn off. Reconnecting to the headphones helps only by reloading the page.

**Comment by lukasIO** [comment]
could you open a separate issue about that? Thanks. 
I'll close this one
