### ISSUE TITLE
Importing `@livekit/components-styles` errors

### ISSUE THREAD

**Issue by nbrustein** [livekit/components-js#1058]
### Select which package(s) are affected

\@livekit/components-styles

### What is happening

I have a jest spec that imports a file with the following import:

```
import '@livekit/components-styles';
```

That triggers the error:

```
SyntaxError: Unexpected token '{'
```

I've run into similar problems with the css from other libraries, so I generally skip css imports in jest specs with this configuration:

```
moduleNameMapper: {
    '\\.(css|less|scss)$': 'identity-obj-proxy',
}
```

tbh, I don't understand this stuff very well, so I don't know exactly why that didn't apply to the css from livekit.
I managed to work around this by mocking out the import, like:

```
moduleNameMapper: {
    '@livekit/components-styles':
            '<rootDir>/__mocks__/@livekit/components-styles.js',
}
```

### What I expect

I should be able to run jest specs when importing `'@livekit/components-styles'` without running into errors.

### Reproduction

Set up a vanilla jest setup with:

```
moduleNameMapper: {
    '\\.(css|less|scss)$': 'identity-obj-proxy',
}
```

Add this to a jest spec

```
import '@livekit/components-styles';
```

Run the spec

### System Info

```shell
System:
    OS: macOS 14.6.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 11.45 GB / 64.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 22.11.0 - ~/.asdf/installs/nodejs/22.11.0/bin/node
    Yarn: 4.5.3 - ~/.asdf/installs/nodejs/22.11.0/bin/yarn
    npm: 10.9.0 - ~/.asdf/plugins/nodejs/shims/npm
  Browsers:
    Chrome: 131.0.6778.205
    Safari: 18.1
```

### Severity

annoyance

**Comment by lukasIO** [comment]
thanks for flagging this. This sounds more like a jest issue with CSS modules rather than one we can fix in this package. Will close this, but feel free to reopen if you have reason to believe this is something that the styles package is doing specifically wrong.
