### ISSUE TITLE
Usage of `useDataChannelMessage`

### ISSUE THREAD

**Issue by brkcrdk** [livekit/components-js#288]
### Describe the problem

In order to use `useDataChannelMessage` we have to specify `channelId` twice. First when we initialize the hook, second when we `send` message with payload like this:

```js
const { send } = useDataChannelMessages({ channelId: 'say_hello' });

const sentRegards = async () => {
    await send({
      channelId: 'say_hello',
      payload: 'Hi mate',
   });
 };
``` 

I know that this is not important and has no impact of our usage of this beautiful library but i think adding `channelId` twice feels weird to me. :D 

### Describe the proposed solution

Either after initializing hook with `channelId`, i think `send` shouldn't require me `channelId` anymore and should only accept payload or we should add channelId within `send` method.

### Importance

nice to have

**Comment by lukasIO** [comment]
yeah, that's a fair point. 
The idea behind it was that we wanted to make it possible to use multiple channelIds within the same hook, so that you could say 
```tsx
const { send } = useDataChannelMessages({ channelId: ['say_hello', 'say_goodbye'] });

const sentRegards = async () => {
    await send({
      channelId: 'say_hello',
      payload: 'Hi mate',
   });
 };
```

but maybe that's actually not needed. 
If we were to restrict the hook to a single `channelId` we could let the `send` method only take the payload type of course.

cc @Ocupe and @keepingitneil for discussing this

**Comment by brkcrdk** [comment]
Oh, i understand now! Thank you for your quick response. :)

**Comment by lukasIO** [comment]
Though about it some more, I think it's more user friendly when the `send` method is simplified. 
It's maybe even nicer to reason about different channel handlers if each of them has their "own" hook

**Comment by brkcrdk** [comment]
Thank you so much for quick response and result! :)
