### ISSUE TITLE
`useParticipants` hook cause rerender!

### ISSUE THREAD

**Issue by brkcrdk** [livekit/components-js#301]
### Select which package(s) are affected

\@livekit/components-react

### Describe the bug

If we add `filter` prop to `useParticipants` hook like in code snippet, it causes rerender.

```js
const participantList = useParticipants({
    filter: participant => participant.isSpeaking,
  });
```

<img width="1208" alt="Ekran Resmi 2023-02-09 17 32 10" src="https://user-images.githubusercontent.com/49235488/217841744-736f2947-54bf-4365-aa99-06c467527813.png">

### Reproduction

- Import `useParticipants` hook from @livekit/components-react
- Paste this code snippet to your hook or component:
  ```js
   const participantList = useParticipants({
    filter: participant => participant.isSpeaking,
  });
  console.log(participantList);
  ```
- You should see rerender error logs on your console. 

### Logs

```shell
-
```

### System Info

```shell
-
```

### Severity

serious, but I can work around it

**Comment by lukasIO** [comment]
thanks for the report! 
yeah, we're currently trying to fix some problems around the filter function.
For now (if this is the actual filter you want to apply) you could use `useSpeakingParticipants`

**Comment by brkcrdk** [comment]
Thank you @lukasIO, i understand.

I need different kind of filtering but i added that to give much simple example :D  i will make workaround until you fix then. Thank you so much your support 🙏🏻

**Comment by davidzhao** [comment]
Curious, what type of filtering are you trying to perform? Looking to understand the type of things folks may need here.

**Comment by brkcrdk** [comment]
I have two type of partcipant inside the room. `Admin` and `User`. `Admin` can see all the participants but `User` can't see them. `Admin` can select some participants and make them featured. When admin select a user,  selected users sid is shared by all participants with my socket implementation that i added. In the end i need to filter all particisipants that are featured.

**Comment by lukasIO** [comment]
How do you differentiate between admin and user? 
do they have different metadata that you use to figure it out? 
or a list of identities/sids?

**Comment by brkcrdk** [comment]
Yes, i will do it like that. Thank you for support 🙏🏻
