### ISSUE TITLE
Should `useRemoteParticipants` hook require any prop?

### ISSUE THREAD

**Issue by brkcrdk** [livekit/components-js#302]
### Describe the problem

If we use `useRemoteParticipants` hook without adding any prop to it gives typescript error.

```js
// Gives Error
 const remoteParticipants = useRemoteParticipants();

// Works
 const remoteParticipants = useRemoteParticipants({});
 ```

![Ekran Resmi 2023-02-09 17 39 46](https://user-images.githubusercontent.com/49235488/217843653-1f461fec-ca61-4985-ba0f-57990a1f1353.png)

### Describe the proposed solution

I think it should work like `useParticipants` hook.

### Importance

nice to have

**Comment by lukasIO** [comment]
you're totally right! we addressed this today/yesterday, it's just not released yet :)
