### ISSUE TITLE
Can't connect to room in Firefox

### ISSUE THREAD

**Issue by grogou** [livekit/components-js#362]
### Select which package(s) are affected

\@livekit/components-core

### Describe the bug

I have disconnected or not connected to room in Windows Firefox browser. 
Similar like this on MacOS, but it is disconnected after 2-3 page refresh.

### Reproduction

Just create room and try to connect with Firefox browser.

### System Info

```shell
System:
    OS: Linux 5.15 Ubuntu 20.04.5 LTS (Focal Fossa) -> it is WSL2
    CPU: (6) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 7.32 GB / 11.69 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 18.12.1 - ~/.nvm/versions/node/v18.12.1/bin/node
    Yarn: 1.22.19 - /home/linuxbrew/.linuxbrew/bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v18.12.1/bin/npm
  npmPackages:
    livekit-client: ^1.6.5 => 1.6.5
```

### Severity

blocking all usage of LiveKit

**Comment by lukasIO** [comment]
hi @grogou, 

thanks for the report! 
Please include browser logs for your reports so that we can track see what's happening.

I just tested on FF Windows on meet.livekit.io and it works without a problem. 
Are you using a self hosted instance of LiveKit or Cloud?

**Comment by grogou** [comment]
It happens when I need to give access for microphone and camera, after that I get this on console.
```Error: could not connect PeerConnection after timeout
    LivekitError errors.ts:5
    ConnectionError errors.ts:22
    connectTimeout Room.ts:376
    setTimeout handler*CriticalTimers.setTimeout timers.ts:8
    connectFn Room.ts:372
    promise utils.ts:256
    Future utils.ts:252
    connect Room.ts:403
    useLiveKitRoom ParticipantTile.tsx:115
    React 8
    workLoop scheduler.development.js:266
    flushWork scheduler.development.js:239
    performWorkUntilDeadline scheduler.development.js:533
    js scheduler.development.js:571
    js scheduler.development.js:633
    __require chunk-MB5FDF5C.js:12
    js index.js:6
    __require chunk-MB5FDF5C.js:12
    React 2
    __require chunk-MB5FDF5C.js:12
    js React
    __require chunk-MB5FDF5C.js:12
    js React
    __require chunk-MB5FDF5C.js:12
    <anonymous> react-dom_client.js:38```

After page refresh when access is allowed for mic and cam it is working.

I am using LiveKit Cloud.

**Comment by lukasIO** [comment]
thanks for the info, can you tell me which Firefox version you are using?
In case it is 110 or greater, could you try it with 109? 
In my tests the issue only started with v110. 

Cannot reproduce a connection error on MacOS however

**Comment by grogou** [comment]
Same problem with v109.

I have joined to Slack. Will share with you details today. 

Thank you))
