### ISSUE TITLE
Conflicting styles from @livekit/components-styles and @mui

### ISSUE THREAD

**Issue by helderjbe** [livekit/components-js#384]
### Select which package(s) are affected

\@livekit/components-styles

### Describe the bug

When importing styles from @livekit/components-styles, styles shouldn't be polluting the global scope.

Because of this, styles imported conflict with other packages like @mui

This is the example with the style conflicting with the textfield
<img width="961" alt="Screenshot 2023-03-28 at 22 00 24" src="https://user-images.githubusercontent.com/35939017/228366258-5204b44f-20d9-4198-91b6-aacc918e5a81.png">

This is the example with the livekit style disabled:
<img width="961" alt="Screenshot 2023-03-28 at 22 00 37" src="https://user-images.githubusercontent.com/35939017/228366386-cf116286-0992-410c-8f8c-ba24bf04f63f.png">

### Reproduction

Use @mui and @livekit in a project -> implement textfield

### System Info

```shell
System:
    OS: macOS 13.2.1
    CPU: (8) arm64 Apple M2
    Memory: 200.45 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.17.0 - ~/.nvm/versions/node/v16.17.0/bin/node
    Yarn: 1.22.19 - ~/Documents/xxxx/node_modules/.bin/yarn
    npm: 8.19.1 - ~/.nvm/versions/node/v16.17.0/bin/npm
  Browsers:
    Chrome: 111.0.5563.146
    Safari: 16.3
  npmPackages:
    livekit-client: ^1.7.1 => 1.7.1
```

### Severity

blocking an upgrade

**Comment by lukasIO** [comment]
hi @helderjbe,

thanks for the report! 
we're trying not to pollute any global scope by scoping the styles to specific elements.
In your example the scope where style is applied is `.lk-room-container`. 
Does the textfield live within your livekit-room? 

cc @mdo

**Comment by helderjbe** [comment]
Yes. In my use case, I'm using importing LiveKitRoom in the entry point App (where context providers are instantiated). I want users to be able to talk even though they are not on the room page.
