### ISSUE TITLE
About Pagination system

### ISSUE THREAD

**Issue by abbaslanbay** [livekit/components-js#426]
### Describe the problem

Hello guys, When there are too many users, it will not fit on the screen. I think a pagination structure can be made. For example, when it exceeds 6 people, it needs to be posted on the 2nd page, in this way, the cost can be reduced and it can be more efficient.

### Describe the proposed solution

We added manually but you should do this for library

### Importance

would make my life easier

**Comment by abbaslanbay** [comment]
![Screenshot 2023-04-08 at 13 12 30](https://user-images.githubusercontent.com/45471774/230715797-f9279912-12bf-4e0f-b638-95990c4e5e5f.png)
![Screenshot 2023-04-08 at 13 12 47](https://user-images.githubusercontent.com/45471774/230715798-9e55fbb6-3d91-44c6-9a4b-72ecc8c8a5e8.png)

**Comment by Ocupe** [comment]
Hey @abbaslanbay, thank you for your suggestion!
Depending on your version, you may not have noticed, but we've added pagination with the [`usePagination`](https://github.com/livekit/components-js/blob/main/packages/react/src/hooks/usePagination.ts) hook to the `GridLayout`. Currently, the maximum number of visible participants is determined solely by the width of the `GridLayout`, but we plan to add some more customisation options (like maximum visible participants) to make it easier for developers to modify it.

**Comment by abbaslanbay** [comment]
Hi @Ocupe thanks for your response. However I didn't understant how can i use pagination system
For example that code 
` <LiveKitRoom
          token={token}
          serverUrl={liveKitUrl}
          options={roomOptions}
          video={userChoices.videoEnabled}
          audio={userChoices.audioEnabled}
          onDisconnected={onLeave}
        >
          <VideoConference chatMessageFormatter={formatChatMessageLinks} />
        </LiveKitRoom>`
        
        Can you send me sample code

**Comment by Ocupe** [comment]
`@abbaslanbay The VideoConference component is what we call a prefab. Prefabs are ready-made components that are built using other, more low-level components that you can use as a drop-in solution. They are opinionated and not as flexible/customizable as the lower level components.
If you like the general direction of the `VideoConferenc` component, but want to make some changes to it that are beyond the options given to you by the properties. Then you can simply create a custom `VideoConferenc` component. 

You would start by copying and pasting the existing implementation of the [`VideoConferenc`](https://github.com/livekit/components-js/blob/main/packages/react/src/prefabs/VideoConference.tsx) component into a file, for example `MyCustomVideoConferenc`. MyCustomVideoConferenc` is now a drop in replacement for `VideoConferenc` and if you replace it, nothing should have changed. With this setup you now have access to the implementation of `MyCustomVideoConferenc`, you can start modifying the implementation to your liking.

You can now drill down further and replace the `GridLayout` component in your `MyCustomVideoConferenc` component with your own implementation just like you just did with the `VideoConferenc`. If you do this, you will have all the freedom to build the implementation of a grid layout that you want. 

We are still working on our documentation, but there is also a short guide on how to implement a custom component. https://github.com/livekit/components-js/blob/main/docs/alpha-docs/guides/custom-components.md

**Comment by lukasIO** [comment]
@abbaslanbay if there's additional things you'd like to see around the new pagination system, feel free to open another issue, I will close this one as done as we have pagination built in in the `GridLayout` component now.
