### ISSUE TITLE
Getting error while turbo build

### ISSUE THREAD

**Issue by apurvbhavsar** [livekit/components-js#466]
### Select which package(s) are affected

\@livekit/components-styles, \@livekit/components-core

### Describe the bug

![image](https://user-images.githubusercontent.com/68545259/234267409-f58afebb-49e3-4bab-b07d-1875ab4a2137.png)

### Reproduction

Cloned and install dependency using yarn. Then hit the build command.

### System Info

```shell
System:
    OS: Windows 10 10.0.19045
    CPU: (8) x64 Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz
    Memory: 8.48 GB / 15.86 GB
  Binaries:
    Node: 18.16.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 9.6.4 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 112.0.5615.138
    Edge: Spartan (44.19041.1266.0), Chromium (112.0.1722.58)
    Internet Explorer: 11.0.19041.1566
```

### Severity

annoyance

**Comment by lukasIO** [comment]
can you post the entire logs as text? it says "no files found" for the styles package, which is odd. 

does the same happen on WSL ?

**Comment by lukasIO** [comment]
ah nice, does it also still work with escaped quotes `\"**/*.scss\"` ?

**Comment by apurvbhavsar** [comment]
yes, it worked.

**Comment by lukasIO** [comment]
great! would you like to submit a PR to fix the issue?

**Comment by apurvbhavsar** [comment]
yes, doing it
