### ISSUE TITLE
Using options in LiveKitRoom component breaks app

### ISSUE THREAD

**Issue by helderjbe** [livekit/components-js#488]
### Select which package(s) are affected

\@livekit/components-react

### What I'm expecting
I want to be able to set the connection options in LiveKitRoom react component without facing any issues

### What happens instead
When connecting, I face the following error:

<img width="1482" alt="Screenshot 2023-05-22 at 13 11 35" src="https://github.com/livekit/components-js/assets/35939017/fb57e9eb-ebe7-48ef-9a03-4dc1536bb562">

### Reproduction

1 - Use any setup with LiveKitRoom react component

2 - Add options prop to that component. Here's mine (using the simple example in a fresh git clone):

```
<LiveKitRoom
  token={token}
  serverUrl={process.env.NEXT_PUBLIC_LK_SERVER_URL}
  connect={connect}
  onConnected={() => setIsConnected(true)}
  onDisconnected={handleDisconnect}
  audio={true}
  video={true}
  // HERE vvvv
  options={{
    adaptiveStream: true,
    dynacast: true,
    stopLocalTrackOnUnpublish: true,
    videoCaptureDefaults: {
      resolution: VideoPresets.h360.resolution,
    },
  }}
  ////////////////////
>

...
```

3 - Start server and connect

4 - Profit

### System Info

```shell
System:
    OS: macOS 13.3.1
    CPU: (8) arm64 Apple M2
    Memory: 113.72 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.20.0 - ~/.nvm/versions/node/v16.20.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.20.0/bin/yarn
    npm: 8.19.4 - ~/.nvm/versions/node/v16.20.0/bin/npm
  Browsers:
    Chrome: 113.0.5672.126
    Safari: 16.4
```

### Severity

serious, but I can work around it

**Comment by lukasIO** [comment]
Hi!
I cannot reproduce this on the nextjs example. 
Can you enable debug logging with `setLogLevel('debug')` and post the logs as text?
