### ISSUE TITLE
Pinned/focused screen share track cannot be unpinned/unfocused

### ISSUE THREAD

**Issue by richthegxd** [livekit/components-js#500]
### Select which package(s) are affected

\@livekit/components-react

### Describe the bug

Hello everyone, I have encountered a bug in my and your application. The demo window or the user's camera does not decrease by clicking on the button.

I fixed this bug in my application by removing the focusTrack?.publication?.trackSid property from the useEffect dependencies in VideoConference.tsx.

I also ran into another problem, when focusing on another window, an error appears in the console and the focus window does not work as it should.

I attach a video with these bugs:
https://www.awesomescreenshot.com/video/17791574?key=becb61b26ece2ccc3dabc3dfec1e87a6

### Reproduction

https://www.awesomescreenshot.com/video/17791574?key=becb61b26ece2ccc3dabc3dfec1e87a6

### System Info

```shell
System:
    OS: Linux 5.15 Ubuntu 22.04.1 LTS 22.04.1 LTS (Jammy Jellyfish)
    CPU: (2) x64 AMD Ryzen 5 5600X 6-Core Processor
    Memory: 2.67 GB / 4.81 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 16.19.0 - ~/.nvm/versions/node/v16.19.0/bin/node
    npm: 8.19.3 - ~/.nvm/versions/node/v16.19.0/bin/npm
  npmPackages:
    livekit-client: 1.9.7 => 1.9.7
    @livekit/components-react: 1.0.3 => 1.0.3
    @livekit/components-styles: 1.0.0 => 1.0.0
```

### Severity

annoyance

**Comment by lukasIO** [comment]
the video you attached doesn't seem to work, I get a `invalid share key` error when clicking the link!

**Comment by richthegxd** [comment]
@lukasIO sorry, my bad, a have attached a new video

**Comment by lukasIO** [comment]
thanks! cc @Ocupe

**Comment by Ocupe** [comment]
This should fix the problem described here, where the track in focus could not be unfocused: #519
The `Error while running updatePages()` in the console does not seem to be related to the bug described in this issue.

**Comment by Ocupe** [comment]
Close this and open a new issue for the `Error while running updatePages()` bug. #524
