### ISSUE TITLE
Publish 2 Video Tracks

### ISSUE THREAD

**Issue by rchoffar** [livekit/components-js#547]
### Describe the problem

I wanted to be able to publish 2 videos devices for a project but i am not able to, exept by instanciate 2 LiveKitRoom and publish a video in each LiveKitRoom.
But this cause problemes in order to use the sdk properly

### Describe the proposed solution

I would suggest to take a list of video devices and a list of audio devices instead of just 1
Each video devices could be a participant

### Importance

I cannot use LiveKit without it

**Comment by davidzhao** [comment]
you can implement this with components, simply publish tracks yourself with the Room object instead of relying on the automatic behavior.
