### ISSUE TITLE
SyntaxError: Named export 'useDebounce' not found. [usehooks-ts]

### ISSUE THREAD

**Issue by sawariz0r** [livekit/components-js#592]
### Select which package(s) are affected

\@livekit/components-react

### Describe the bug

Started getting this in the latest version (1.1.1), had to roll back to 1.1.0.
Seems to be an issue with the dependency `usehooks-ts`.

### Reproduction

Installing and running with 1.1.1 seems to cause the issue. 
Reverting to 1.1.0 solves the issue.

### Logs

```shell
file:///Users/[user]/[folder]/[project]/[project-package]/node_modules/@livekit/components-react/dist/index.mjs:1966
import { useDebounce, useIntersectionObserver } from "usehooks-ts";
         ^^^^^^^^^^^
SyntaxError: Named export 'useDebounce' not found. The requested module 'usehooks-ts' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'usehooks-ts';
const { useDebounce, useIntersectionObserver } = pkg;
```

### System Info

```shell
System:
    OS: macOS 13.3.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 122.53 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.11.0 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 8.19.2 - /opt/homebrew/bin/npm
    pnpm: 7.14.0 - /opt/homebrew/bin/pnpm
    Watchman: 2022.10.24.00 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome: 115.0.5790.170
    Safari: 16.4
  npmPackages:
    livekit-client: ^1.6.2 => 1.12.0 
    @livekit/components-react: ^1.0.7 => 1.1.1
```

### Severity

blocking all usage of LiveKit

**Comment by lukasIO** [comment]
thanks for the report! which package manager are you using and which nextjs version (or in case it isn't nextjs, what bundler are you using?)

**Comment by sawariz0r** [comment]
I'm using yarn primarily. Using next `13.1.4` :)

**Comment by lukasIO** [comment]
thanks, I was able to reproduce it once but now it seems to work on subsequent installs/runs. 
I linked two issues in the PR, one of them being a usehooks-ts issue talking about exactly this problem. If it turns out to be tricky to solve, we might as well get rid of that dependency again.

**Comment by sawariz0r** [comment]
Happy to test it if you need it, just let me know!

**Comment by lukasIO** [comment]
Could you try again with `1.1.2`? thanks!

**Comment by sawariz0r** [comment]
@lukasIO It works and went through the build just fine. Thanks a bunch!
