### ISSUE TITLE
Start Audio button shows up inconsistently even when audio is connected

### ISSUE THREAD

**Issue by sparkplug0025** [livekit/components-js#670]
### Select which package(s) are affected

\@livekit/components-react

### Describe the bug

The "StartAudio" button is intended to appear only when the browser blocks audio playback. However, there are instances where this button appears even if the user has already successfully connected with audio.

### Expected behavior:
The "StartAudio" button should only display if the browser is blocking audio playback.

### Actual behavior:
The "StartAudio" button sometimes displays even when the user can hear and talk to other participants.

### Reproduction

The issue doesn't consistently reproduce. However, the most common way to reproduce it is:

1. Use various browsers.
2. Disable audio permissions.
3. Connect to the meeting and subsequently allow the audio settings.
4. Observe that even though you can communicate with other participants, the "StartAudio" button is still visible.

Users have reported encountering this issue on Chrome, Brave, Firefox, Microsoft Edge, and Safari.

### System Info

```shell
OS: Ubuntu 20.04.6
Browsers tested: Chrome, Brave, Microsoft Edge, Firefox
```

### Severity

annoyance

### Additional Information

Here's an example of the "StartAudio" button being visible before I allowed audio:
![image](https://github.com/livekit/components-js/assets/79721020/d7d1f969-667b-40b4-a820-875dd9484a0c)

After clicking "Allow", I was able to communicate with other participants, but the button remained visible:
![image](https://github.com/livekit/components-js/assets/79721020/d21044c3-2fd9-4ab4-8891-cac32e4b6a1e)

**Comment by lukasIO** [comment]
Thanks for the report. 
Could you provide debug logs `setLogLevel('debug')` for when that happens?

**Comment by lukasIO** [comment]
Thinking more about this, this might be related to the fact that some browsers choose to allow playback after microphone permissions have been granted (need to verify this). 
Currently there's no way to listen to an event to observe that permission status. 
What we'd probably want to do is to call `startAudio` whenever a user successfully acquired a local audio track.
