### ISSUE TITLE
Customize or add buttons in the ParticipantTile component

### ISSUE THREAD

**Issue by klk2** [livekit/components-js#709]
### Describe the problem

I wanted to implement the screenshot function of a single participant. At first, I implemented it by outsourcing a layer of divs, but there was a problem that I could not detect the camera status of the participants.

I currently put it in the upper right corner, I hope it can be defined to the lower right corner

<img width="496" alt="image" src="https://github.com/livekit/components-js/assets/19720619/e9369c94-4b59-4af7-9bd7-5eab858fe6c7">

I went to inherit and implement participants, but some hooks or references were not exposed.

### Describe the proposed solution

It would be better if there is a child with a custom button, and more buttons for individual participants can be customized.

### Importance

nice to have

**Comment by lukasIO** [comment]
what hooks and/or references weren't exposed? We can fix that at the source

**Comment by klk2** [comment]
> what hooks and/or references weren't exposed? We can fix that at the source

ParticipantPlaceholder
useIsEncrypted
optional: LockLockedIcon, ScreenShareIcon
