### ISSUE TITLE
`localParticipant` which was returned by `useLocalParticipant` does not have correct connection state

### ISSUE THREAD

**Issue by y-mimura** [livekit/components-js#731]
### Select which package(s) are affected

\@livekit/components-react

### What I'm expecting
The `RTCEngine.isClosed` state which is held in `localParticipant`'s instance returned by `useLocalParticipant` is correctly synchronised with the room state.

### What happens instead
The `RTCEngine.isClosed` state which is held in `localParticipant`'s instance returned by `useLocalParticipant` is not correctly synchronised with the room state.
We can avoid this issue by getting `localParticipant` from `room` which was returned by `useRoomContext`. However, I believe that is not expected behavior.

### Reproduction

This is what it looks like if you extract the relevant section from my code.

```tsx
const room = useLiveKitRoom(/* some options*/);

return <RoomContext.Provider>{children}</RoomContext.Provider>

// inside of the RoomContext
const { localParticipant } = useLocalParticipant();
const [stream, setStream] = useState<MediaStream | false>(false);

useEffect(() => {
  if (typeof stream === 'boolean') {
    localParticipant.setScreenShareEnabled(false);
    return;
  }
  const [track] = stream.getVideoTracks();
  // debug: value of isClosed is true even if the localParticipant was connected to the room.
  console.log('isClosed', localParticipant.engine.isClosed);
  // track publishing was failed by error "cannot publish track when not connected"
  localParticipant.publishTrack(track, { source: Track.Source.ScreenShare });
}, [stream])
```

### System Info

```shell
Not needed
```

### Severity

serious, but I can work around it

**Comment by lukasIO** [comment]
you're using internal state when accessing `engine` on the local participant. 
use `useConnectionState` for figuring out what connection state a room is currently in

**Comment by lukasIO** [comment]
yeah, you should only initiate track publishing once the room is already connected! 
You can also use the <TrackToggle/> component (or inspect the `useTrackToggle` hook to see how we do this internally)
