### ISSUE TITLE
Screen share is not working on mobile

### ISSUE THREAD

**Issue by Lakshmi203** [livekit/components-js#767]
### Select which package(s) are affected

\@livekit/components-react

### Describe the bug

localParticipant?.setScreenShareEnabled(true); is not working on mobile phone

### Reproduction

Try to join on meeting in https://meet.livekit.io/ from phone

### System Info

```shell
Windows 11
```

### Severity

blocking all usage of LiveKit

**Comment by lukasIO** [comment]
this is a browser restriction for mobile phones, that's why we cannot support it, see https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getDisplayMedia#browser_compatibility
