### ISSUE TITLE
Uncaught (in promise) DOMException: Requested device not found

### ISSUE THREAD

**Issue by AurimasG12** [livekit/components-js#772]
### Select which package(s) are affected

\@livekit/components-react

### Describe the bug

I'am excepting to have no errors in console.

### Reproduction

1. open https://meet.livekit.io/ with chrome incognito tab having only microphone device
2. Try to join meeting
3. Open up console and check the errors

### Logs

```shell
error while setting up prejoin DOMException: Requested device not found
Uncaught (in promise) DOMException: Requested device not found
```

### System Info

```shell
System:
    OS: Linux 5.15 Ubuntu 20.04.6 LTS (Focal Fossa)
    CPU: (6) x64 Intel(R) Core(TM) i5-9400F CPU @ 2.90GHz
    Memory: 8.36 GB / 15.56 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 18.17.0 - ~/.nvm/versions/node/v18.17.0/bin/node
    Yarn: 3.6.3 - ~/.yarn/bin/yarn
    npm: 9.6.7 - ~/.nvm/versions/node/v18.17.0/bin/npm
    Watchman: 4.9.0 - /usr/bin/watchman
  Browsers:
    Chrome: 115.0.5790.170
  npmPackages:
    livekit-client: ^1.15.8 => 1.15.8
```

### Severity

annoyance

**Comment by davidzhao** [comment]
Hi @AurimasG12, could you attach the full stacktrace?

**Comment by AurimasG12** [comment]
> Hi @AurimasG12, could you attach the full stacktrace?

`error while setting up prejoin DOMException: Requested device not found` just this error in prejoin

**Comment by lukasIO** [comment]
the error in the console should show you a stacktrace of where exactly (which function calls) the error originates from. That's what we'd need

**Comment by AurimasG12** [comment]
> the error in the console should show you a stacktrace of where exactly (which function calls) the error originates from. That's what we'd need

`[name].tsx:65 error while setting up prejoin DOMException: Requested device not found`

```js
   <PreJoinNoSSR
              onError={(err) => console.log('error while setting up prejoin', err)}
              defaults={{
                username: '',
                videoEnabled: true,
                audioEnabled: true,
              }}
              onSubmit={handlePreJoinSubmit}
            ></PreJoinNoSSR>
```

**Comment by lukasIO** [comment]
ah, ok, then why not just change that console log line? 
It sounds like your main issue is the fact, that there's an error being logged to the console? 
This error is only being logged in the meet repo itself and not within the components repo
