### ISSUE TITLE
Request functionality for changing audio output

### ISSUE THREAD

**Issue by pouyaafraz123** [livekit/components-js#773]
### Describe the problem

I want to have functionality that change user active speaker when user is already joined the meet 

### Describe the proposed solution

There is another hook (useMediaDeviceSelect) that can change audio input and camera i want this hook support audio ouput too or other function or hook provided for doing that

### Importance

would make my life easier

**Comment by lukasIO** [comment]
hi, 

this is supported already today by setting `audiooutput` as the `MediaDeviceKind`. 
https://docs.livekit.io/reference/components/react/hook/usemediadeviceselect/
