### ISSUE TITLE
Start Video button always shows up

### ISSUE THREAD

**Issue by Psychiquest** [livekit/components-js#780]
### Select which package(s) are affected

\@livekit/components-react

### Reproduction

Just have a normal UI with video enabled, and it will show up.

### System Info

```shell
I am using React components
```

### Severity

serious, but I can work around it

### Additional Information

In `useStartVideo.ts` file, we're using state from an ensured room, and using this parameter to check if `roomEnsured.canPlaybackVideo` is true to know if video is enabled or not. However, no such parameter exists in `ensuredRoom ` object. That's why it will ideally show up everytime in react builds (at least)

**Comment by lukasIO** [comment]
Hi, could you please run `npx envinfo --system --binaries --browsers --npmPackages "{livekit-client, @livekit/*}"` and post the result?
This seems like a version mismatch of livekit-client and components

**Comment by Psychiquest** [comment]
This is the output of that command
  
System:
    OS: Windows 11 10.0.22621
    CPU: (16) x64 AMD Ryzen 7 5800H with Radeon Graphics
    Memory: 2.44 GB / 15.41 GB
  Binaries:
    Node: 18.12.1 - C:\Program Files\nodejs\node.EXE
    npm: 9.5.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Chromium (122.0.2365.52)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    livekit-client: ^1.13.2 => 1.13.2

**Comment by lukasIO** [comment]
thanks for some reason, the interesting bit, the `@livekit/components-react` version does not show up. Which version do you have installed? 
You should be able to fix this (assuming you're on a components 1.x version) by installing the latest 1.x livekit-client version with `npm i livekit-client@v1.15.12`
