### ISSUE TITLE
If you close the web page directly, it will take a while for the remote subscriber to receive the leave message, and the screen will not move and stay (> 5-10s) In mobile browsers

### ISSUE THREAD

**Issue by klk2x** [livekit/components-js#799]
### Select which package(s) are affected

\@livekit/components-core, \@livekit/components-react

### Describe the bug

The subscriber opens it on the PC segment, and the publisher directly closes the web page or tab after joining the room on the mobile terminal.
If directly close the tab to exit instead of clicking hang up, the subscriber's screen will freeze, and it will take >5-10 seconds before the subscriber is considered to have left the meeting.

### Reproduction

After entering the room, turn on the camera, connect directly to the web page or tab

### System Info

```shell
cross platform
```

### Severity

annoyance

**Comment by klk2x** [comment]
Room participants all open and close in the PC browser and there is no such problem.

**Comment by lukasIO** [comment]
Unfortunately there's now way to work around this. It will take a couple of seconds on an abrupt leave of a participant until the server can safely mark it as disconnected.

**Comment by klk2x** [comment]
@lukasIO
