### ISSUE TITLE
Cannot share camera after screen sharing

### ISSUE THREAD

**Issue by adcimon** [livekit/components-js#804]
### Select which package(s) are affected

\@livekit/components-react

### What I'm expecting

Participant A enters a room, shares the screen and enables the camera (a participant B is already in the room). Participant B sees the screen shared **AND** the camera.

### What happens instead

Participant A enters a room, shares the screen and enables the camera (a participant B is already in the room). Participant B sees the screen shared but **NOT** the camera.

### Reproduction
Reproduced with the VideoConference component.

1. Participant A enters a room.
2. Participant B enters a room.
3. Participant A shares the screen.
4. Participant B can see the screen shared.
5. Participant A enables the camera.
6. Participant B cannot see the camera.

### System Info

```shell
"@livekit/components-react": "2.0.3"
"livekit-client": "2.0.2"

Although it didn't work on previous versions.
```

### Severity

serious, but I can work around it

**Comment by lukasIO** [comment]
> Reproduced with the VideoConference component.

I just tried this on meet.livekit.io and following your repro steps. And B can see the camera of A. 

Can you reproduce this there as well?
If so, please post logs.

**Comment by davidzhao** [comment]
What is the browser and the version?

**Comment by adcimon** [comment]
Participant A: Firefox 124
Participant B: Chrome 122.0.6261.129

It doesn't happen if the participant B (Chrome) is the one who shares. Seems an issue with Firefox.

**Comment by lukasIO** [comment]
thank you, this apparently will have to be fixed in pion, here's the issue tracking it [https://github.com/pion/webrtc/pull/2107](https://github.com/pion/webrtc/pull/2107)
