### ISSUE TITLE
Sometimes issue in fetching Publication of remote participants

### ISSUE THREAD

**Issue by Sakthivel-DB** [livekit/components-js#805]
### Select which package(s) are affected

\@livekit/components-core, \@livekit/components-react, examples

### Describe the bug

Sometimes, having issues in fetching publication of remote participants.
If I got correctly, again if I reload the page, can't able to get publication

### Reproduction

When two users try to connect in video meet, publication of local participant will only be fetched.
Both cameras should be turned off initially. If I turn on the video, then I'm getting the publication

### Logs

```shell
trackPublicationCheck 
[{…}]
0
: 
{participant: LocalParticipant, publication: LocalTrackPublication, source: 'camera'}
length
: 
1
[[Prototype]]
: 
Array(0)
```

### System Info

```shell
system : Mac M1
OS : macOS Ventura 
version : 13.5.2

Browser : Brave 1.63.174
```

### Severity

blocking an upgrade

**Comment by lukasIO** [comment]
This is by design. 
With disabled camera, there will be no publications published. They will only publish once the track gets active for the first time.
