### ISSUE TITLE
Allow for a 3x2 grid layout for the GridLayout component

### ISSUE THREAD

**Issue by vandercloak** [livekit/components-js#886]
### Describe the problem

4-6 participants is our use cases sweat spot. At the moment when there are 5-6 participants, it uses a 3x3 grid layout.

Is it possible to allow for a 3x2 grid layout (or allow us to override the GRID_LAYOUTS variable)?

![image](https://uploads.linear.app/65f9603c-a265-4a1f-8af0-4c2243b87ade/fda8fa64-e692-4511-996c-8825b687f904/bac66e04-305f-4395-b034-f43f46dbbe33?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzY1Zjk2MDNjLWEyNjUtNGExZi04YWYwLTRjMjI0M2I4N2FkZS9mZGE4ZmE2NC1lNjkyLTQ1MTEtOTk2Yy04ODI1YjY4N2Y5MDQvYmFjNjZlMDQtMzA1Zi00Mzk1LWIwMzQtZjQzZjQ2ZGJiZTMzIiwiaWF0IjoxNzE3NzUyNjg3LCJleHAiOjMzMjg4MzEyNjg3fQ.OJL1i8ndQyF1AmlimIq4iuRpXHWJCp8tJbErGc04Xwk "=826x")

### Describe the proposed solution

Allow for the customizing/overwritting of the layouts OR to add this entry to `GRID_LAYOUTS`

```tsx
{
    columns: 3,
    rows: 2,
    name: "3x2",
    minTiles: 5,
    maxTiles: 6,
    minWidth: 700,
    minHeight: 0
},

### Alternatives considered

_No response_

### Importance

I cannot use LiveKit without it

### Additional Information

_No response_
```

**Comment by Ocupe** [comment]
Hi @vandercloak, I agree with you, which is why we changed this a while ago. Are you on the latest version? We added a pure CSS solution https://github.com/livekit/components-js/commit/fd776c36b9857ae8a1029131148ac73ae11c2df3. You can get the desired behaviour by changing one line. Let us know if this works for you?

**Comment by vandercloak** [comment]
This is great news. I will try it out today. Thanks @Ocupe for getting back to me so quick!

**Comment by vandercloak** [comment]
@Ocupe Is there any fix for this for the react version of live kit?

"@livekit/components-core": "^0.10.2",
"@livekit/components-react": "2.3.2",
"@livekit/components-styles": "1.0.12",
"livekit-client": "2.2.0",

**Comment by Ocupe** [comment]
It should work when you update the @livekit/components-styles package. You can see it in action in the [Meet](https://meet.livekit.io/) application. Make sure your grid has the correct CSS properties applied to it (like [here](https://github.com/livekit/components-js/commit/fd776c36b9857ae8a1029131148ac73ae11c2df3)).
