### ISSUE TITLE
The `autoSubscribe` is not by default true

### ISSUE THREAD

**Issue by konsalex** [livekit/components-js#981]
### Select which package(s) are affected

\@livekit/components-core, \@livekit/components-react, examples

### Describe the bug

Not sure this is related to this repo or to [this one](https://github.com/livekit/client-sdk-js), but the default value is not `autoSubscribe: true` as also described in the docs:

https://docs.livekit.io/realtime/client/receive/

### Reproduction

This is visible in some examples as here:
https://github.com/livekit-examples/meet/blob/bf86c02e591925114d10e77505a38d0898903986/app/custom/VideoConferenceClientImpl.tsx#L56

### System Info

```shell
Not needed
```

### Severity

serious, but I can work around it

### Additional Information

Either fix the docs to reflect the default, or actually make this the default

**Comment by davidzhao** [comment]
it does default to true, as shown [here](https://github.com/livekit/client-sdk-js/blob/57bf8abdc735203ea180e1265fe86a9f6fe4f1a3/src/room/defaults.ts#L44).

It's totally fine to explicitly set it, as we do in some of the examples

**Comment by konsalex** [comment]
Indeed @davidzhao . I think the issue was that the parent element that was passing the token in the context of livekit was not re-creating it without a `key` property. Leaving this here in case someone stumbles upon this issue in React.

```diff
<LiveKitRoom
+++   key={token}
      token={token}
      serverUrl={URLS.SERVER_WS}
      connect={true}
      connectOptions={{
        autoSubscribe: true,
      }}
    > ... </LiveKitRoom>
```
